### ISSUE TITLE
Every request fails: missing field `chain`

### ISSUE THREAD

**Issue by 0atman** [wisespace-io/nettfiske#10]
certstream seem to have changed their API:
```
[2020-12-10][16:31:43] Received unknown message: missing field `chain` at line 1 column 1813
[2020-12-10][16:31:43] Received unknown message: missing field `chain` at line 1 column 1919
[2020-12-10][16:31:43] Received unknown message: missing field `chain` at line 1 column 1606
[2020-12-10][16:31:43] Received unknown message: missing field `chain` at line 1 column 1794
```

**Comment by 0atman** [comment]
https://github.com/wisespace-io/nettfiske/blob/master/src/data.rs#L10

**Comment by 0atman** [comment]
Confirmed, the api for Certstream has changed to no longer include `chain` https://certstream.calidog.io/example.json

**Comment by 0atman** [comment]
This was caused by upstream https://github.com/CaliDog/certstream-server/pull/56

**Comment by 0atman** [comment]
our workaround has been to remove `chain` from the data model, and then remove all code that expected it. (we're only interested in domain names for our usage)
https://github.com/wisespace-io/nettfiske/blob/master/src/data.rs#L10

**Comment by 0atman** [comment]
https://github.com/wisespace-io/nettfiske/blob/master/src/data.rs#L10

**Comment by wisespace-io** [comment]
@0atman  thank you for troubleshooting the issue. I will remove the Chain Object.

**Comment by 0atman** [comment]
Thank you for making this great library :-)

**Comment by d-Rickyy-b** [comment]
Hi there, just wanted to note, that the chain object is still available but only for the full stream: `wss://certstream.calidog.io/full-stream`

So you can still use the chain (if you want) - you just need to parse it differently.
Compare these two json samples from the live certstream API at `certstream.calidog.io`:

[full-stream](https://pastebin.com/88zh0bKg) vs. [regular stream](https://pastebin.com/HLi4BUWt)

**Comment by wisespace-io** [comment]
@d-Rickyy-b I can add again in a near future.  Thank you for pointing out it.
