### ISSUE TITLE
Tag releases?

### ISSUE THREAD

**Issue by snake66** [wisespace-io/nettfiske#4]
Would it be an idea to tag releases? Makes it a bit easier for us trying to build packages from the repo.
Thanks!

**Comment by wisespace-io** [comment]
I was updating the .toml file, but as it is not a library it makes more sense to use tags.

See below:

https://github.com/wisespace-io/nettfiske/releases

**Comment by snake66** [comment]
Awesome! A good idea to keep both the toml and the tags in sync, I guess.
Thanks!
