### ISSUE TITLE
Send notifications to Telegram/slack

### ISSUE THREAD

**Issue by wisespace-io** [wisespace-io/nettfiske#6]
1. Should be turned off by default
2. Should be based on specified threshold

**Comment by snake66** [comment]
irc, Mattermost and Matrix would be more interesting, actually. Perhaps make it pluggable?

Then again, it's quite trivial to write a filter to do this based on the log output instead. Perhaps native syslog support would be more interesting?

**Comment by wisespace-io** [comment]
A plugin mechanism sounds good, however it can be archived watching the logs, it may be more flexible.
It may be an option https://github.com/Geal/rust-syslog
